---
- name: Reload systemd controller
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart video-mask controller
  ansible.builtin.systemd:
    name: video-mask-controller
    state: restarted

- name: Restart video-mask autoscaler
  ansible.builtin.systemd:
    name: video-mask-autoscaler
    state: restarted

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
